---
version: "3.7"
services:
  redis:
    image: redis
    ports: ["6379:6379"]
  db:
    image: postgres:9.4
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  rabbitmq:
    image: rabbitmq
    ports: ["5672:5672"]
  sonarqube:
    image: sonarqube
    ports: ["9000:9000"]
