---
version: "3.7"
services:
  redis:
    image: redis
    ports: ["6379:6379"]
  db:
    image: postgres:11
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  rabbitmq:
    image: rabbitmq:management
    ports: ["5672:5672"]
  wiremock:
    image: rodolpheche/wiremock:latest-alpine
    ports:
      - "12345:8080"
    volumes:
      - ./docs/wiremock:/home/wiremock
