api:
  image:
    repository: "registry:9999/app"
  scaling:
    min: 1
    max: 3
    threshold: 50
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  environment:
    - name: API_JWT_SECRET
      value: "secret"
    - name: API_REDIS_URL
      value: "redis://app-redis-ha"
    - name: API_RABBITMQ_USERNAME
      value: guest
    - name: API_RABBITMQ_PASSWORD
      value: guest
    - name: API_RABBITMQ_HOST
      value: "app-rabbitmq-ha"
    - name: API_RABBITMQ_PORT
      value: "5672"
    - name: API_DATABASE_URL
      value: "jdbc:postgresql://db/app"
    - name: API_DATABASE_USERNAME
      value: "user"
    - name: API_DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-postgresql
          key: password
    - name: API_DATABASE_MAXPOOLSZE
      value: "20"
    - name: JAVALIN_HTTP2_PORT
      value: "8080"
    - name: JAVALIN_HTTPS2_PORT
      value: "8443"
