apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-api
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
    app: {{ .Chart.Name }}
    type: api
